name: 'Execution Guard'
description: 'Blocks any shell command not explicitly allowed by policy. Default = DENY.'
author: 'Nick-heo-eg'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  command:
    description: 'Command to execute (e.g. "echo hello" or "npm run build")'
    required: true
  policy_path:
    description: 'Path to policy YAML file'
    required: false
    default: './policy.yaml'
  fail_on_hold:
    description: 'Exit 1 on HOLD verdict (false = warn + exit 0)'
    required: false
    default: 'true'

outputs:
  verdict:
    description: 'ALLOW, STOP, or HOLD'
  proposal_hash:
    description: 'SHA256 hash of the execution proposal'
  reason:
    description: 'Reason for the verdict'

runs:
  using: 'node20'
  main: 'dist/index.js'
